# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy requirements file and install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Define environment variables, if needed (optional)
# ENV VARIABLE_NAME=value

# Expose a port if your app requires it (optional)
# EXPOSE 5000

# Define the default command to run your app
# Adjust according to the main file to start the server (for example, server_gui.py)
CMD ["python", "server_gui.py"]
