name: CI/CD for Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Copy application files to Azure VM
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" * ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:~/Chat-Webapp/

      - name: Deploy application on Azure VM
        env:
          FLASK_APP: server.py
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          cd ~/Chat-Webapp
          source venv/bin/activate
          pip install -r requirements.txt
          ~/start.sh
          EOF

      - name: Start application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "systemctl start chat-webapp"
