name: CI/CD for Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy application files to Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "mkdir -p ~/Chat-Webapp"
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no -r * ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:~/Chat-Webapp/

      - name: Deploy application on Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          # Force terminate any running instances of server.py
          pkill -f server.py || true  # Ignore error if no process is found
          
          # Optional: Wait for a moment to ensure the process is terminated
          sleep 2
          
          # Check for remaining instances of server.py
          if pgrep -f server.py > /dev/null; then
              echo "Still running after pkill. Attempting to find and kill by port."
              # Find PID by port (5000)
              for pid in $(lsof -t -i:5000); do
                  echo "Killing process $pid running on port 5000"
                  kill -9 $pid
              done
          fi
          
          # Navigate to the application directory and install dependencies
          cd ~/Chat-Webapp
          pip install --user -r requirements.txt

          # Start the Flask application in the background
          nohup flask run --host=0.0.0.0 > flask.log 2>&1 &
          EOF
