name: CI/CD for Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up SSH with password authentication
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass

      - name: Pull latest changes on Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          cd ~/Chat-Webapp
          git reset --hard
          git pull origin main
          pip install --user -r requirements.txt
          nohup python server.py > app.log 2>&1 &
          EOF
