deploy:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: python-app

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AZURE_VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy application files to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no -r Chat-Webapp/* ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:~/app/

    - name: Deploy application on Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
        cd ~/Chat-Webapp
        # Ensure dependencies are installed (adjust based on your app's requirements)
        pip install -r requirements.txt
        # Start or restart your application (replace with your app's startup command)
        nohup python server.py > app.log 2>&1 &
        EOF
