name: CI/CD for Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Copy application files to Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} "mkdir -p ~/Chat-Webapp"
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no -r * ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }}:~/Chat-Webapp/

      - name: Deploy application on Azure VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_HOST }} << 'EOF'
          # Stop any existing Flask server or process using port 5000
          fuser -k 5000/tcp || true
          pkill -f "flask run" || true
          sleep 2

          # Navigate to the application directory and install dependencies
          cd ~/Chat-Webapp
          pip install --user -r requirements.txt

          # Start the Flask server
          echo "Starting Flask server..."
          nohup python3 server.py > flask.log 2>&1 &

          # Ensure the Flask server started
          sleep 5
          if netstat -tuln | grep 5000; then
              echo "Flask server started successfully on port 5000."
          else
              echo "Failed to start Flask server."
              exit 1
          fi
          EOF
